// app.js - Main application functionality
document.addEventListener('DOMContentLoaded', function() {
    console.log("App initialized");
    
    // Auth modal functionality
    const signInButton = document.getElementById('sign-in-button');
    const authModal = document.getElementById('auth-modal');
    const authModalClose = document.querySelector('.auth-modal-close');
    
    if (signInButton) {
        signInButton.addEventListener('click', function() {
            console.log("Sign in button clicked");
            if (authModal) {
                authModal.classList.add('active');
            }
        });
    }
    
    if (authModalClose) {
        authModalClose.addEventListener('click', function() {
            console.log("Auth modal close clicked");
            if (authModal) {
                authModal.classList.remove('active');
            }
        });
    }
    
    if (authModal) {
        authModal.addEventListener('click', function(e) {
            if (e.target === authModal) {
                console.log("Clicked outside auth modal");
                authModal.classList.remove('active');
            }
        });
    }
    
    // AI option selection
    const aiOptions = document.querySelectorAll('.ai-option');
    
    aiOptions.forEach( option => {
        option.addEventListener('click', function() {
            console.log("AI option selected:", this.getAttribute('data-mode'));
            // Remove selected class from all options
            aiOptions.forEach(opt => opt.classList.remove('selected'));
            
            // Add selected class to clicked option
            this.classList.add('selected');
        });
    });
    
    // Legal content functionality
    const mainCard = document.getElementById('main-card');
    const legalContent = document.getElementById('legal-content');
    const legalTitle = document.getElementById('legal-title');
    const legalBody = document.getElementById('legal-body');
    const backButton = document.getElementById('back-to-main');
    
    // Get all legal links
    const legalLinks = document.querySelectorAll('.legal-link');
    
    // Legal content
    const legalTexts = {
        disclaimer: {
            title: "Legal Disclaimer",
            content: `
                <h3>Disclaimer for Star Galaxy</h3>
                <p>The information provided by Star Galaxy ("we," "us," or "our") on our website and application is for general informational purposes only. All information is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information.</p>
                
                <h3>No Professional Advice</h3>
                <p>Our website and application offer an AI-powered idea analysis tool. The analyses, evaluations, and suggestions provided are generated by artificial intelligence and should not be considered as professional or expert advice. Before taking any actions based on the information provided, we strongly recommend consulting with qualified professionals in the relevant fields, including but not limited to legal, financial, and business advisors.</p>
                
                <h3>Patent and Legal Information</h3>
                <p>Any information regarding patents, intellectual property, or legal considerations is provided for informational purposes only and does not constitute legal advice. Patent laws and intellectual property regulations vary significantly across different jurisdictions and are subject to change. We do not guarantee the accuracy or completeness of any patent similarity analysis or legal considerations provided through our service.</p>
                
                <h3>No Liability</h3>
                <p>In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of our website or application.</p>
            `
        },
        terms: {
            title: "Terms of Service",
            content: `
                <h3>Terms of Service for Star Galaxy</h3>
                <p>These Terms of Service govern your use of the Star Galaxy website and application operated by Star Galaxy ("we," "us," or "our"). By accessing or using our service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.</p>
                
                <h3>Use License</h3>
                <p>Permission is granted to temporarily use our website and application for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:</p>
                <p>- Modify or copy the materials<br>
                - Use the materials for any commercial purpose<br>
                - Attempt to decompile or reverse engineer any software contained on Star Galaxy's website or application<br>
                - Remove any copyright or other proprietary notations from the materials<br>
                - Transfer the materials to another person or "mirror" the materials on any other server</p>
                
                <h3>User Content</h3>
                <p>Our service allows you to input ideas and receive AI-generated analysis. You retain all rights to your ideas and content. However, by submitting content to our service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, adapt, and publish the content for the purpose of providing our service to you.</p>
            `
        },
        privacy: {
            title: "Privacy Policy",
            content: `
                <h3>Privacy Policy for Star Galaxy</h3>
                <p>At Star Galaxy, accessible from our website and application, one of our main priorities is the privacy of our users. This Privacy Policy document contains types of information that is collected and recorded by Star Galaxy and how we use it.</p>
                
                <h3>Information We Collect</h3>
                <p>When you use our idea analysis service, we may collect the following information:</p>
                <p>- The ideas and content you input for analysis<br>
                - Usage data such as how you interact with our application<br>
                - Technical data such as your IP address, browser type, and device information</p>
                
                <h3>How We Use Your Information</h3>
                <p>We use the information we collect in various ways, including to:</p>
                <p>- Provide, operate, and maintain our service<br>
                - Improve, personalize, and expand our service<br>
                - Understand and analyze how you use our service<br>
                - Develop new features, products, and services</p>
            `
        }
    };
    
    // Add click event to legal links
    legalLinks.forEach( link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            console.log("Legal link clicked:", this.getAttribute('data-content'));
            
            // Close auth modal if open
            if (authModal && authModal.classList.contains('active')) {
                authModal.classList.remove('active');
            }
            
            // Get content type from data attribute
            const contentType = this.getAttribute('data-content');
            
            // Get content from our content object
            const content = legalTexts[contentType];
            
            if (content) {
                // Set content title and body
                legalTitle.textContent = content.title;
                legalBody.innerHTML = content.content;
                
                // Hide main content and show legal content
                mainCard.style.display = 'none';
                legalContent.style.display = 'block';
                
                // Scroll to top
                window.scrollTo(0, 0);
                
                console.log("Displayed legal content:", contentType);
            }
        });
    });
    
    // Back button functionality
    if (backButton) {
        backButton.addEventListener('click', function() {
            console.log("Back button clicked");
            // Hide legal content and show main content
            legalContent.style.display = 'none';
            mainCard.style.display = 'block';
            
            // Scroll to top
            window.scrollTo(0, 0);
        });
    }
    
    // Analyze button functionality
    const analyzeButton = document.getElementById('analyze-button');
    const ideaText = document.getElementById('idea-text');
    const resultsContainer = document.getElementById('results-container');
    
    if (analyzeButton) {
        analyzeButton.addEventListener('click', function() {
            console.log("Analyze button clicked");
            // Get selected mode
            const selectedMode = document.querySelector('.ai-option.selected').getAttribute('data-mode');
            
            // Get idea text
            const idea = ideaText.value.trim();
            
            if (idea) {
                console.log("Analyzing idea in mode:", selectedMode);
                // Show loading state
                resultsContainer.style.display = 'block';
                resultsContainer.innerHTML = `
                    <div class="ai-thinking">
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="dot"></div>
                    </div>
                `;
                
                // In a real app, you would call your AI service here
                // For now, we'll just simulate a delay
                setTimeout(function() {
                    // This would be replaced with actual AI analysis results
                    showDummyResults(idea, selectedMode);
                }, 2000);
            } else {
                alert('Please enter an idea to analyze.');
            }
        });
    }
    
    // Function to show dummy results (for demonstration)
    function showDummyResults(idea, mode) {
        console.log("Showing results for mode:", mode);
        let results = '';
        
        switch (mode) {
            case 'analyze':
                results: `
                    <h3>Business Analysis</h3>
                    <div class="analysis-summary">
                        <p>Your idea: "${idea}" has been analyzed for business potential. Here's what our AI found:</p>
                        <p>This concept shows promise in the current market environment. The key strengths are its innovative approach and potential for scalability. However, there are some challenges to consider regarding market entry and competition.</p>
                    </div>
                    
                    <div class="scores-container">
                        <div class="score-item">
                            <div class="score-title">Innovation Score</div>
                            <div class="score-circle good">82</div>
                        </div>
                        <div class="score-item">
                            <div class="score-title">Market Potential</div>
                            <div class="score-circle medium">68</div>
                        </div>
                        <div class="score-item">
                            <div class="score-title">Feasibility</div>
                            <div class="score-circle medium">75</div>
                        </div>
                    </div>
                `;
                break;
                
            case 'market':
                results = `
                    <h3>Market Research</h3>
                    <div class="analysis-summary">
                        <p>We've analyzed the market potential for: "${idea}"</p>
                        <p>Our market analysis indicates there is a growing demand in this sector. The target demographic appears to be expanding, with particular interest from the 25-45 age group. Competition exists but there are opportunities for differentiation.</p>
                    </div>
                    
                    <div class="scores-container">
                        <div class="score-item">
                            <div class="score-title">Market Size</div>
                            <div class="score-circle good">85</div>
                        </div>
                        <div class="score-item">
                            <div class="score-title">Competition</div>
                            <div class="score-circle medium">62</div>
                        </div>
                        <div class="score-item">
                            <div class="score-title">Growth Potential</div>
                            <div class="score-circle good">79</div>
                        </div>
                    </div>
                `;
                break;
                
            case 'improve':
                results = `
                    <h3>Idea Improvement</h3>
                    <div class="analysis-summary">
                        <p>We've analyzed your idea: "${idea}" and have suggestions for improvement:</p>
                        <p>Your core concept is solid, but could benefit from some refinements. Consider expanding the target audience and exploring additional revenue streams. We've also identified some potential features that could enhance user engagement.</p>
                    </div>
                    
                    <div class="scores-container">
                        <div class="score-item">
                            <div class="score-title">Original Strength</div>
                            <div class="score-circle medium">70</div>
                        </div>
                        <div class="score-item">
                            <div class="score-title">Improvement Potential</div>
                            <div class="score-circle good">88</div>
                        </div>
                        <div class="score-item">
                            <div class="score-title">Implementation Ease</div>
                            <div class="score-circle medium">65</div>
                        </div>
                    </div>
                `;
                break;
        }
        
        resultsContainer.innerHTML = results;
    }
    
    // Sidebar menu functionality
    const menuItems = document.querySelectorAll('.sidebar-menu li');
    
    menuItems.forEach( item => {
        item.addEventListener('click', function() {
            const page = this.getAttribute('data-page');
            console.log("Menu item clicked:", page);
            
            // Only do something for the dashboard page for now
            if ( page === 'dashboard') {
                // Set this item as active
                menuItems.forEach(i => i.classList.remove('active'));
                this.classList.add('active');
                
                // Show main content, hide legal content
                mainCard.style.display = 'block';
                legalContent.style.display = 'none';
            }
        });
    });
    
    // Social auth buttons
    const socialAuthButtons = document.querySelectorAll('.social-auth-button');
    
    socialAuthButtons.forEach( button => {
        button.addEventListener('click', function() {
            const provider = this.id.split('-')[0];
            console.log("Auth button clicked:", provider);
            alert(`${provider} authentication would happen here in a real app.`);
        });
    });
});

                
