[functions]
  directory = "netlify/functions"
  [functions.environment]
    ALLOWED_ORIGINS = "https://insightforgem.netlify.app"

[[headers]]
  # Apply security headers to all routes.  These headers are set at
  # the CDN edge to provide defence in depth against XSS, clickjacking
  # and other attacks.  See MDN and OWASP guidance for details.
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://cdn-icons-png.flaticon.com; connect-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "no-referrer"
