[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Не секретные настройки по контекстам деплоя
[context.production.environment]
  ROLES_JSON = '{"admin":[],"design":[],"gen":["OPENAI_KEY_GEN"],"guard":[],"research":[],"support":[]}'
  ALLOW_FALLBACK = "false"
  FALLBACK_KEY_NAME = "OPENAI_API_KEY"

[context.deploy-preview.environment]
  ROLES_JSON = '{"gen":["OPENAI_KEY_GEN"],"research":["OPENAI_KEY_RESEARCH"],"support":["OPENAI_KEY_SUPPORT"],"design":[],"admin":[],"guard":[]}'
  ALLOW_FALLBACK = "true"
  FALLBACK_KEY_NAME = "OPENAI_API_KEY"

[context.branch-deploy.environment]
  ROLES_JSON = '{"gen":["OPENAI_KEY_GEN"],"research":[],"support":[],"design":[],"admin":[],"guard":[]}'
  ALLOW_FALLBACK = "true"
  FALLBACK_KEY_NAME = "OPENAI_API_KEY"
